from dotenv import load_dotenv, find_dotenv
import os

load_dotenv(find_dotenv())

RABBITMQ_LOGIN = os.getenv("RABBITMQ_LOGIN")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD")
RABBITMQ_IP = os.getenv("RABBITMQ_IP")
RABBITMQ_PORT = os.getenv("RABBITMQ_PORT")
RABBITMQ_QUEUE_LISTENER = os.getenv('RABBITMQ_QUEUE_LISTENER')
RABBITMQ_QUEUE_SENDER = os.getenv('RABBITMQ_QUEUE_SENDER')
SERVICE_NAME = 'RUNNER TASK FOR RTSP SERVER'
